version: '3.7'
services:

  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    restart: always
    networks:
      - fileDemo-compose-network
  
  fileDemo:
    image: 
    build:
      context: fileDemo-service
      dockerfile: Dockerfile    
    environment:
      RABBIT_URI: tcp://localhost:61616
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - activemq
      
    networks:
      - fileDemo-compose-network

  AlertConsumerService:
    image: 
    build:
      context: AlertConsumerService
      dockerfile: Dockerfile    
    ports:
      - "8082:8082"
    restart: always
    environment:
      
      RABBIT_URI: tcp://localhost:61616
    depends_on:
       - activemq
      
    networks:
      - fileDemo-compose-network
  
# Networks to be created to facilitate communication between containers
networks:
  fileDemo-compose-network: